### ISSUE TITLE
NUNIT_7 Throws Unexpectedly On Integer to Decimal Conversions

### ISSUE THREAD

**Issue by aolszowka** [nunit/nunit.analyzers#83] opened 2018-12-11 14:31 UTC
This may be a duplicate of #50 

Consider the following Test Program

```csharp
namespace NUNIT_7TriggersOnDecimal
{
    using NUnit.Framework;

    [TestFixture]
    public class NUNIT7_TriggersOnDecimalTests
    {
        // Throws NUNIT_7
        [TestCase(-600)]
        public void AssertNegativeDecimal(decimal input)
        {
            Assert.That(input, Is.EqualTo(-600m));
        }

        // No Problem Here
        [TestCase(600)]
        public void AssertPositiveDecimal(decimal input)
        {
            Assert.That(input, Is.EqualTo(600m));
        }
    }
}
```

Part of the problem is related to the fact that you cannot send a decimal in an attribute (see https://github.com/dotnet/roslyn/issues/16898) therefore our Unit Tests were always written to use an Integer constant.

I would not expect NUNIT_7 to throw on the first test case (AssertNegativeDecimal) because it does not throw on the second case. Any thoughts?

**Comment by mikkelbu** [comment] 2018-12-11 19:37
Thanks for the report @aolszowka. It is definitely a bug, but it is not a duplicate of #50 (which is about the return type of methods and async).

The problem is that the logic for extracting the value of the attribute only handles `LiteralExpressionSyntax` (like string and integer literals):
https://github.com/nunit/nunit.analyzers/blob/23cc5b9c9175425d301bed8d99a256a7116574b2/src/nunit.analyzers/Extensions/AttributeArgumentSyntaxExtensions.cs#L17-L20
So `argumentValue` is never set, and hence we report the problem when `Convert.ChangeType` fails to convert `null` to a decimal. So we need to extract the `-600` as an integer, but I'm not sure how to "evaluate" a `LiteralExpressionSyntax` (except by handling all the cases manually, but I hope/think that there is a better approach).

The following will give similar problems, as `x` is not a `LiteralExpressionSyntax`.
```csharp
const int x = 600;

[TestCase(x)]
public void AssertNegativeDecimal(decimal input)
{
    Assert.That(input, Is.EqualTo(-600m));
}
```

**Comment by mikkelbu** [comment] 2018-12-19 14:31
Instead of going via `LiteralExpressionSyntax` we should probably use `SemanticModel.GetConstantValue` to extract the constant value (and since we are in the constructor of an attribute `this.Expression` must be a constant value).

**Closed** 2018-12-19 19:21 UTC
Labels: bug
