### ISSUE TITLE
NUnit1030 when using TestCaseSource and ITestCaseData

### ISSUE THREAD

**Issue by appel1** [nunit/nunit.analyzers#664] opened 2023-12-11 15:09 UTC
```csharp
public static IEnumerable<ITestCaseData> TestData()
{
  yield return new TestCaseData("something").SetName("other").SetCategory("important");
}

[TestCaseSource(nameof(TestData))]
public void TheTest(string s)
{}
```

This gives the error NUnit1030 which I think is incorrect. 

error NUnit1030: The TestCaseSource provides type 'NUnit.Framework.Interfaces.ITestCaseData', but the Test method expects type 'string' for parameter 's' (https://github.com/nunit/nunit.analyzers/tree/master/documentation/NUnit1030.md)

NUnit 3.14
NUnit.Analyzers 3.10

**Comment by manfred-brands** [comment] 2023-12-12 02:31
I think the issue is the interface. Can you declare the enum to be of type `TestCaseData` instead.

**Comment by appel1** [comment] 2023-12-12 14:40
Yes, that worked.

**Comment by manfred-brands** [comment] 2023-12-31 14:13
The NUnit source code casts the `ITestCaseData` instance to the internal class `TestCaseParameters` which is the base class of `TestCaseData`. Any other class implementing the interface would throw a runtime exception resulting in missing test cases.
Also the [nunit documentation](https://docs.nunit.org/articles/nunit/writing-tests/attributes/testcasesource.html#sources-with-expected-result-using-testcasedata) only mentions the class not the interface.

I therefore will close this issue for now.

**Closed by manfred-brands** 2023-12-31 14:13 UTC

**Comment by appel1** [comment] 2023-12-31 14:26
Perhaps the interface should be marked as obsolete then if it is not intended to be used and in many cases does not work?

**Comment by stevenaw** [comment] 2023-12-31 16:44
I agree with you @appel1 that this would benefit from improved clarify. We actually have an issue on the framework side, https://github.com/nunit/nunit/issues/3803, that currently tracks it along with discussions about how to mitigate.
