### ISSUE TITLE
NUnit.Analyzers 4.3.0 missed an Assert.IsAssignableFrom that caused a build error after upgrading to latest NUnit 4.2.2

### ISSUE THREAD

**Issue by MCPtz** [nunit/nunit.analyzers#790] opened 2024-10-28 20:22 UTC
NUnit.Analyzers 4.3.0 missed an Assert.IsAssignableFrom that caused a build error after upgrading to NUnit 4.2.2, from NUnit 3.13.3.

That is there was no build error or warning when on NUnit 3.13.3 and building with NUnit.Analyzers 4.3.0.

Or if there was a warning, I missed it because I had tens of thousands of changes to make.

I suggest this becomes a build error for NUnit.Analyzers.

Fixed manually by doing this:
`Assert.IsAssignableFrom<ClassName>(objectVariable);` -> `Assert.That(objectVariable, Is.AssignableFrom(typeof(ClassName)));`

**Comment by manfred-brands** [comment] 2024-10-28 23:51
@OsirisTerje This slipped through because when I ensured all tests in the legacy assembly were converted, I forgot to check the test coverage. `Assert.IsAssignableFrom` and `Assert.IsNotAssignableFrom` are not tested. I will update the tests and create a analyzer rule for these.

Same for `IsInstanceOf` and `IsNotInstanceOf`.

**Comment by mikkelbu** [comment] 2024-10-30 08:20
I'll close #742 as a duplicate of this

**Closed** 2024-11-12 17:04 UTC
