### ISSUE TITLE
NUNIT_7 does not cater for Task and ValueTask

### ISSUE THREAD

**Issue by chinwobble** [nunit/nunit.analyzers#79] opened 2018-10-03 12:00 UTC
The NUNIT_7 currently returns an error 

```csharp
[TestCase(false, ExpectedResult = 942)]
[TestCase(true, ExpectedResult = 10)]
public Task<int> Sample(bool input)
{
     Task.FromResult(1);
}
```

need to cater for async methods. Analyser needs to check for Task<int> and ValueTask<int> in this case.

Would you accept a PR to fix this?

**Comment by mikkelbu** [comment] 2018-10-03 14:06
Hi @chinwobble 
Isn't this a duplicate of #50? With respect to the PR offer then I think it makes sense to wait for #76, as the problem about `ExpectedResult` and async exists both for `TestCaseAttribute` and for `TestAttribute`, and perhaps we should also for #69, as #69 will make changes in the same area of the code.

I think I'll merge #76 tonight and then see if we can get @304NotModified work in #69 rebased on top of this.

**Comment by 304NotModified** [comment] 2018-10-04 12:17
> @304NotModified work in #69 rebased on top of this.

That's OK with me. But not sure if I have time for this week

**Comment by mikkelbu** [comment] 2019-04-02 19:49
This was partly handled by the changes in #122. So far we only support `Task`. `ValueTask` (not supported by NUnit yet) will be handled by #123.

**Closed by mikkelbu** 2019-04-02 19:49 UTC
