### ISSUE TITLE
NUnit1011 Issue in the Output window while compiling

### ISSUE THREAD

**Issue by tupacko** [nunit/nunit.analyzers#307] opened 2020-11-02 17:25 UTC
Hello,

there seems to be an issue with this rule https://docs.nunit.org/articles/nunit-analyzers/NUnit1011.html

NUnit.Analyzers version: 0.5.0
NUnit: 3.12.0
Visual Studio 2019: 16.7.7

I also created a project showing the issue: https://github.com/tupacko/NUnit1011TypeInOtherAssemblyBug Basically, if the Type the TestCaseSource references is in another Assembly, the rule raises false positive. What is even more interesting, that in the Error List, there is no error, only in the Output window. Also, if the analyzer is disabled, the test compiles and runs (the test case source is found).

Actual: There is a compilation error stating that the SourceName cannot be found. ("error NUnit1011: The TestCaseSource argument 'TheNames' does not specify an existing member.")
Expected: The code should compile.

**Comment by Dreamescaper** [comment] 2020-11-02 18:23
Duplicate of #304

**Comment by mikkelbu** [comment] 2020-11-02 19:02
This should be solved in the next release. A prerelease containing the fix can be found at https://www.myget.org/feed/nunit-analyzers/package/nuget/NUnit.Analyzers/0.6.0-dev-00594 (and newer versions).

**Closed by mikkelbu** 2020-11-02 19:02 UTC

**Comment by tupacko** [comment] 2020-11-02 19:54
Thank you for the update! I'll check out how was it fixed :)
